optimize publish script

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 ################################################################### SETUP ########################################################################
-if ! _SCRIPT_DIR="$(get_script_dir "${BASH_SOURCE[0]}")"; then echo "Error while running: _SCRIPT_DIR=\"\$(get_script_dir \"${BASH_SOURCE[0]}\")\"" && exit 1; fi
+S="${BASH_SOURCE[0]}" && while [ -h "$S" ]; do D="$(cd -P "$(dirname "$S")" && pwd)" && S="$(readlink "$S")" && [[ $S != /* ]] && S="$D/$S"; done && _SCRIPT_DIR="$(cd -P "$(dirname "$S")" && pwd)" && unset S D
 set -o errexit -o errtrace -o nounset
 ##################################################################################################################################################
 # shellcheck disable=SC2155
@@ -15,7 +15,8 @@ NAME
        ${_SCRIPT_NAME}
 
 SYNOPSIS
-       ${_SCRIPT_NAME} [--help] [--debug] [--verbose] [--auto-confirm]
+       ${_SCRIPT_NAME} [--auto-confirm]
+          [--help] [--debug] [--verbose]
 
 EXAMPLES
        ${_SCRIPT_NAME}
@@ -41,7 +42,7 @@ while test $# -gt 0; do
       ;;
     --auto-confirm)
       shift
-      export auto_confirm=true
+      auto_confirm=true
       ;;
     --)
       shift
@@ -63,10 +64,13 @@ function exiting() {
   echo "Exiting..."
   exit "${1:-1}"
 }
+function check_debug() {
+  test "${debug_mode:-}" = "true"
+}
 function confirm() {
   local response=""
   read -r -p "${1:-Are you sure?}"$'\n'"[Y/n]> " response
-  case $response in
+  case "$response" in
     [yY][eE][sS] | [yY] | "") true ;;
     [nN][oO] | [nN]) false ;;
     *)
@@ -87,7 +91,7 @@ function check_git_default_branch() {
   if git is-side-branch; then
     echo "Git repo not on master branch! Make a PR to master first"
     git status
-    exit 1
+    exiting 1
   fi
   return 0
 }
@@ -96,71 +100,167 @@ function check_git_dirty() {
   if git is-dirty; then
     echo "Git repo is dirty!"
     git status
-    exit 1
+    exiting 1
   fi
   return 0
 }
 
-function publish_and_tag() {
+function check_git_missing_commits() {
+  git fetch
+  if git has-incoming-commits; then
+    echo "Git repo is missing commits from remote!"
+    git status
+    exiting 1
+  elif git has-outgoing-commits; then
+    echo "Git repo has local commits!"
+    git status
+    exiting 1
+  fi
+  return 0
+}
+
+function check_version_bumped() {
+  if check_debug; then
+    return 0
+  fi
+
+  if ! git is-dirty; then
+    echo "Bad __custom_next_version_bump function, nothing appears to have been changed"
+    exiting 1
+  fi
+  return 0
+}
+
+function __custom_clean_local() {
+  git clean -Xd --force -- target
+}
+
+function __custom_store_versions() {
+  VERSION_FILE="pom.xml"
+  CURR_VERS="$(make echo-version-current-release)"
+  if test -z "${NEXT_VERS-}"; then
+    NEXT_VERS="$(make echo-version-next-minor)"
+  fi
+  export VERSION_FILE CURR_VERS NEXT_VERS
+}
+
+function __custom_publish() {
+  if check_debug; then
+    echo make version-release
+    echo git commit -m "v${CURR_VERS}" -- "$VERSION_FILE"
+    echo make deploy
+    echo git push
+  else
+    make version-release
+    git commit -m "v${CURR_VERS}" -- "$VERSION_FILE"
+    make deploy
+    git push
+  fi
+}
+
+function __custom_next_version_bump() {
+  if check_debug; then
+    echo make version-bump-minor-snapshot
+  else
+    make version-bump-minor-snapshot
+  fi
+}
+
+function clean_local() {
+  __custom_clean_local
+}
+
+function store_versions() {
+  __custom_store_versions
+
+  if test -z "${VERSION_FILE-}"; then
+    echo "Bad __custom_store_versions function, VERSION_FILE variable not set"
+    exiting 1
+  elif test -z "${CURR_VERS-}"; then
+    echo "Bad __custom_store_versions function, CURR_VERS variable not set"
+    exiting 1
+  elif test -z "${NEXT_VERS-}"; then
+    echo "Bad __custom_store_versions function, NEXT_VERS variable not set"
+    exiting 1
+  fi
+  return 0
+}
+
+function publish_command() {
   check_git_dirty
-  make version-release
-  VERS="v$(make echo-version-current)"
-  export VERS
 
-  if ! confirm_with_auto "Commit, tag, and deploy version ${VERS}?"; then
+  if ! confirm_with_auto "Publish version ${CURR_VERS}?"; then
     exiting 1
   fi
 
-  git commit -m "$VERS" -- pom.xml
-  git tag "$VERS"
-  make deploy
+  __custom_publish
 }
 
-function push_published() {
-  if ! confirm_with_auto "Push updates for version ${VERS}?"; then
+function tag_version() {
+  if ! confirm_with_auto "Tag version ${CURR_VERS}?"; then
     exiting 1
   fi
 
-  git push
-  git push --tags
+  if check_debug; then
+    echo git tag "v${CURR_VERS}"
+    echo git push --tags
+  else
+    git tag "v${CURR_VERS}"
+    git push --tags
+  fi
 }
 
-function next_vers() {
-  if ! confirm_with_auto "Bump ${VERS} to next minor version?"; then
+function _next_version_branch() {
+  if check_debug; then
+    echo git checkout -b "$NEXT_BRANCH"
+    echo git push --set-upstream origin "$NEXT_BRANCH"
+  else
+    git checkout -b "$NEXT_BRANCH"
+    git push --set-upstream origin "$NEXT_BRANCH"
+  fi
+}
+
+function _next_version_commit() {
+  if check_debug; then
+    echo git commit -m "Prepare next version" -- "$VERSION_FILE"
+  else
+    git commit -m "Prepare next version" -- "$VERSION_FILE"
+  fi
+}
+
+function next_version() {
+  check_git_dirty
+
+  NEXT_BRANCH="${NEXT_BRANCH:-dev-v${NEXT_VERS}}"
+  export NEXT_BRANCH
+
+  if ! confirm_with_auto "Bump ${CURR_VERS} to next minor version (${NEXT_VERS}) in a new branch (${NEXT_BRANCH})?"; then
     exiting 0
   fi
-  check_git_dirty
 
-  make version-bump-minor
-  NEXT_RELEASE_VERS="v$(make echo-version-current)"
-  make version-snapshot
-  SNAPSHOT_VERS="v$(make echo-version-current)"
-  export NEXT_RELEASE_VERS SNAPSHOT_VERS
+  _next_version_branch
+  __custom_next_version_bump
+  check_version_bumped
+  _next_version_commit
 
-  if ! confirm_with_auto "Push updates for next minor version ${SNAPSHOT_VERS}?"; then
-    exiting 1
-  fi
-
-  git commit -m "Prepare next version" -- pom.xml
-  git push
-}
-
-function next_vers_branch() {
-  NEXT_BRANCH="dev-${NEXT_RELEASE_VERS}"
-
-  if ! confirm_with_auto "Create new development branch for next version: ${NEXT_BRANCH}?"; then
+  if ! confirm_with_auto "Push version bump updates to new branch ${NEXT_BRANCH}?"; then
     exiting 0
   fi
 
-  git checkout -b "$NEXT_BRANCH"
-  git push --set-upstream origin "$NEXT_BRANCH"
+  if check_debug; then
+    echo git push
+  else
+    git push
+  fi
 }
 
 cd "$_SCRIPT_DIR"
 
 check_git_default_branch
 check_git_dirty
-publish_and_tag
-push_published
-next_vers
-next_vers_branch
+check_git_missing_commits
+clean_local
+store_versions
+publish_command
+tag_version
+next_version
